// Steven Raden AA 1160995
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM = 
" o __\n" + 
" | / \\\n" + 
" |/      _\n" + 
" |     _| |_\n" + 
" ^    | | | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o \n" + 
" |   \\\n" + 
" |----|  _\n" + 
" |   / _| |_\n" + 
" ^    | | | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o __\n" + 
" | / \\\n" + 
" |/      _\n" + 
" |      | |_\n" + 
" ^      | | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o \n" + 
" |   \\\n" + 
" |----|  _\n" + 
" |   /  | |_\n" + 
" ^      | | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o __\n" + 
" | / \\\n" + 
" |/      \n" + 
" |         _\n" + 
" ^        | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o \n" + 
" |   \\\n" + 
" |----|  \n" + 
" |   /     _\n" + 
" ^        | |\n" + 
"/ \\\n" + 
"=====\n" + 
" o __\n" + 
" | / \\     0\n" + 
" |/       000\n" + 
" |       00000\n" + 
" ^      0000000\n" + 
"/ \\    000000000\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;